### ISSUE TITLE
RankSystem Support

### ISSUE THREAD

**Issue by BroCrows** [AmmyR/InfoTag#2]
Add support for the plugin [RankSystem](poggit.pmmp.io/p/RankSystem)

**Comment by BroCrows** [comment]
Link didnt work
poggit.pmmp.io/p/RankSystem

**Comment by AmmyRQ** [comment]
Done. See [latest changes](https://github.com/AmmyR/InfoTag/compare/feea26edc315c467daf87227ee8b097ec27da3bc...b316593ad080c2ec9efd744baa970fa03ffdb14a?diff=unified) for more information.
