### ISSUE TITLE
Version 4.0.0

### ISSUE THREAD

**Issue by Willtom999** [AmmyR/InfoTag#3]
Plz add version 4.0.0

**Comment by Willtom999** [comment]
Api 4.0.0

**Comment by AmmyRQ** [comment]
See [latest changes](https://github.com/AmmyR/InfoTag/compare/db87f1f299d1a77073f958694eb09416fdc35605...9f91cc30ae1077d66065fe7a46f7a1fb5cb7b3d6) for more information.
